## PREDICTION EXPANDING METER2

In [1]:
#http://stackoverflow.com/questions/11845055/predicting-from-previous-datevalue-data
import matplotlib.pyplot as plt
import pandas as pd # v. 1.7
import MySQLdb
import numpy as np
import time
import sys
import datetime 
from datetime import datetime
from sympy import *
from sympy.solvers import solve
from sympy.parsing.sympy_parser import parse_expr
from sklearn.metrics import mean_absolute_error,mean_squared_error
import statistics 
%matplotlib inline

import MySQLdb
def initial_trend(series, slen):
    sum = 0.0
    for i in range(slen):
        sum += float(series[i+slen] - series[i]) / slen
    return sum / slen

# >>> initial_trend(series, 12)
# -0.7847222222222222

def triple_exponential_smoothing(series, slen, alpha, beta, gamma, n_preds):
    result = []
    seasonals = initial_seasonal_components(series, slen)
    for i in range(len(series)+n_preds):
        if i == 0: # initial values
            smooth = series[0]
            trend = initial_trend(series, slen)
            result.append(series[0])
            continue
        if i >= len(series): # we are forecasting
            m = i - len(series) + 1
            result.append((smooth + m*trend) + seasonals[i%slen])
        else:
            val = series[i]
            last_smooth, smooth = smooth, alpha*(val-seasonals[i%slen]) + (1-alpha)*(smooth+trend)
            trend = beta * (smooth-last_smooth) + (1-beta)*trend
            seasonals[i%slen] = gamma*(val-smooth) + (1-gamma)*seasonals[i%slen]
            result.append(smooth+trend+seasonals[i%slen])
    return result

# # forecast 24 points (i.e. two seasons)
# >>> triple_exponential_smoothing(series, 12, 0.716, 0.029, 0.993, 24)
# [30, 20.34449316666667, 28.410051892109554, 30.438122252647577, 39.466817731253066, ...


def initial_seasonal_components(series, slen):
    seasonals = {}
    season_averages = []
    n_seasons = int(len(series)/slen)
    # compute season averages
    for j in range(n_seasons):
        season_averages.append(sum(series[slen*j:slen*j+slen])/float(slen))
    # compute initial values
    for i in range(slen):
        sum_of_vals_over_avg = 0.0
        for j in range(n_seasons):
            sum_of_vals_over_avg += series[slen*j+i]-season_averages[j]
        seasonals[i] = sum_of_vals_over_avg/n_seasons
    return seasonals
##-----------------------------------------------------------------------------------
from sklearn.metrics import mean_squared_error
def fittingparameter(data_y,j):
    count_alpha = 0
    count_beta = 0
    count_gamma = 0
    alpha = float(0)
    beta = float(0)
    gamma = float(0)
    index_alpha =[]
    index_beta =[]
    index_gamma = []
    act = j
    data = data_y
    pred_no = 1
    ramda = 0.1
    MSE_holtload = []
#     query1 = "SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '%s' AND TimeStamp <= '%s';"% (time_b[act+1],time_b[act+96])
    query1 = "SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '%s' ;"% (time_b[act+1])
    print query1
    df1 = pd.read_sql(query1, conn)
#     print len(df)
    while (alpha <= float(1)):
        count_alpha += 1
        beta = float(0)
        while (beta <=float(1)):
            count_beta += 1 
            gamma = float(0)
            while (gamma <= float(1)):
                count_gamma += 1
                pred_h = triple_exponential_smoothing(data, 96*7,alpha,beta ,gamma, pred_no)
                pred_data = pred_h[len(pred_h)-(pred_no):]                                               
                MSE = mean_squared_error (df1.Sub_metering_2, pred_data)   
#                 print MSE              
                MSE_holtload.append(MSE)
                index_alpha.append(alpha)
                index_beta.append(beta)
                index_gamma.append(gamma)     
#                 print index_alpha,index_beta,index_gamma
                gamma += ramda
            beta += ramda
        alpha += ramda  
#     print  count_gamma,count_beta,count_alpha    
    index_MSE = MSE_holtload.index(min(MSE_holtload))
#     print min(MSE_holtload)
#     print index_MSE
    MSE_min = MSE_holtload[index_MSE]
    alpha = index_alpha[index_MSE]
    beta = index_beta[index_MSE]
    gamma= index_gamma[index_MSE]
    print count_alpha,count_beta,count_gamma
    print MSE_min,alpha,beta,gamma
    return (alpha,beta,gamma)

In [3]:
conn = MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()
query = "SELECT Timestamp,active_power FROM prediction.data15min_4y WHERE Timestamp >= '%s'   AND TimeStamp <= '%s';"% ("2007-01-01 00:14:59","2007-03-31 23:59:59")
df = pd.read_sql(query, conn , index_col=['Timestamp'])

pred_no = 1 # power 1 Data/15min in 1Hr --> 60/15 = 4 and 1day = 4*24 = 96
j = 0
i = 0
d = len(df)/96 
day = 0

conn = MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()

time_a = pd.date_range('2007-01-01 00:14:59', periods=d*96, freq='15T')
time_b = pd.date_range('2007-01-14 23:59:59', periods=(d*96)+1, freq='15T')

# set databases to empty 
query_empty = """truncate table prediction.pred_expand_mt2""" 
c.execute(query_empty)

while (j < 96*d ) :    
    if (j%96 == 0):    
        day += 1
        print "_________DAY:" ,day
        print "\n"
    print "data at :" , j,">>>", time_b[j+1]
    query = "SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '%s'   AND TimeStamp <= '%s';"% (time_a[0],time_b[j])
    print query
    df = pd.read_sql(query, conn)
    conn.commit()
    data_y = df['Sub_metering_2'].values.tolist()  
    ans_fiting = fittingparameter(data_y,j)
    pred_h = triple_exponential_smoothing(data_y, 96*7, ans_fiting[0], ans_fiting[1], ans_fiting[2],1)
    pred_data = pred_h[len(pred_h)-(pred_no):]
    c.execute("INSERT INTO prediction.pred_expand_mt2 (Timestamp, watt_sub2) VALUES ( %s, %s)",(time_b[j+1],abs(pred_data[0])))
    conn.commit()
    j += 1
print "DONE!!"

 DAY: 1
data at : 0 >>> 2007-01-15 00:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-14 23:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:14:59' ;
11 121 1331
0.0 1.0 1.0 0.0
data at : 1 >>> 2007-01-15 00:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 00:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:29:59' ;
11 121 1331
0.0 1.0 1.0 0.0
data at : 2 >>> 2007-01-15 00:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 00:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:44:59' ;
11 121 1331
5.73002410573e-05 0.8 1.0 0.3
data at : 3 >>> 2007-01-15 00:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 00:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:59:59' ;
11 121 1331
0.0037264058526 0.2 0.0 0.7
data at : 4 >>> 2007-01-15 01:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 00:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:14:59' ;
11 121 1331
0.000540996131842 0.2 0.0 0.9
data at : 5 >>> 2007-01-15 01:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 01:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:29:59' ;
11 121 1331
0.149802303352 0.2 0.4 0.0
data at : 6 >>> 2007-01-15 01:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 01:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:44:59' ;
11 121 1331
0.0206562639774 0.4 0.2 0.9
data at : 7 >>> 2007-01-15 01:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 01:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:59:59' ;
11 121 1331
0.00243535128761 0.8 1.0 0.3
data at : 8 >>> 2007-01-15 02:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 01:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:14:59' ;
11 121 1331
3.62310428799e-05 0.9 1.0 0.4
data at : 9 >>> 2007-01-15 02:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 02:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:29:59' ;
11 121 1331
0.00815273974466 0.9 0.0 0.0
data at : 10 >>> 2007-01-15 02:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 02:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:44:59' ;
11 121 1331
0.00901665442452 0.0 0.2 0.6
data at : 11 >>> 2007-01-15 02:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 02:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:59:59' ;
11 121 1331
0.000322300903508 0.8 0.7 0.4
data at : 12 >>> 2007-01-15 03:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 02:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:14:59' ;
11 121 1331
0.000646896385605 0.7 0.5 0.9
data at : 13 >>> 2007-01-15 03:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 03:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:29:59' ;
11 121 1331
0.00165919289652 0.4 0.3 0.0
data at : 14 >>> 2007-01-15 03:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 03:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:44:59' ;
11 121 1331
3.22505827076e-05 0.8 0.8 0.5
data at : 15 >>> 2007-01-15 03:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 03:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:59:59' ;
11 121 1331
8.98728325355e-07 0.4 0.0 0.5
data at : 16 >>> 2007-01-15 04:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 03:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:14:59' ;
11 121 1331
1.36945318477e-05 0.5 0.6 1.0
data at : 17 >>> 2007-01-15 04:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 04:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:29:59' ;
11 121 1331
0.000123612251414 0.3 0.8 0.9
data at : 18 >>> 2007-01-15 04:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 04:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:44:59' ;
11 121 1331
0.00784823419228 0.2 0.6 0.1
data at : 19 >>> 2007-01-15 04:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 04:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:59:59' ;
11 121 1331
2.5428942226e-06 0.7 0.3 0.7
data at : 20 >>> 2007-01-15 05:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 04:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:14:59' ;
11 121 1331
0.000153878030518 0.3 0.2 1.0
data at : 21 >>> 2007-01-15 05:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 05:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:29:59' ;
11 121 1331
0.00666391747623 0.2 0.2 0.9
data at : 22 >>> 2007-01-15 05:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 05:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:44:59' ;
11 121 1331
0.000152266689428 0.6 0.2 1.0
data at : 23 >>> 2007-01-15 05:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 05:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:59:59' ;
11 121 1331
0.000245237807316 0.2 0.1 0.9
data at : 24 >>> 2007-01-15 06:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 05:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:14:59' ;
11 121 1331
1.619481651e-06 0.3 0.1 0.7
data at : 25 >>> 2007-01-15 06:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 06:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:29:59' ;
11 121 1331
0.0864664789346 0.2 0.8 0.5
data at : 26 >>> 2007-01-15 06:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 06:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:44:59' ;
11 121 1331
1.79030580865e-05 0.5 0.4 0.3
data at : 27 >>> 2007-01-15 06:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 06:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:59:59' ;
11 121 1331
0.00188116099494 0.2 0.4 1.0
data at : 28 >>> 2007-01-15 07:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 06:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:14:59' ;
11 121 1331
0.000358750359261 0.8 0.5 1.0
data at : 29 >>> 2007-01-15 07:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 07:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:29:59' ;
11 121 1331
0.000190086151926 0.4 0.2 0.2
data at : 30 >>> 2007-01-15 07:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 07:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:44:59' ;
11 121 1331
1.36762992316e-06 0.8 0.5 0.2
data at : 31 >>> 2007-01-15 07:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 07:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:59:59' ;
11 121 1331
0.0 1.0 1.0 0.2
data at : 32 >>> 2007-01-15 08:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 07:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:14:59' ;
11 121 1331
0.00176371307661 0.3 0.7 0.9
data at : 33 >>> 2007-01-15 08:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 08:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:29:59' ;
11 121 1331
0.00121819640303 0.8 1.0 1.0
data at : 34 >>> 2007-01-15 08:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 08:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:44:59' ;
11 121 1331
2.24996272433e-05 0.2 1.0 0.1
data at : 35 >>> 2007-01-15 08:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 08:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:59:59' ;
11 121 1331
9.47441727843e-06 1.0 0.0 0.0
data at : 36 >>> 2007-01-15 09:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 08:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:14:59' ;
11 121 1331
7.20510710276e-05 0.7 0.7 1.0
data at : 37 >>> 2007-01-15 09:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 09:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:29:59' ;
11 121 1331
0.00136571035548 0.1 1.0 0.5
data at : 38 >>> 2007-01-15 09:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 09:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:44:59' ;
11 121 1331
0.000116324301385 0.1 0.2 0.3
data at : 39 >>> 2007-01-15 09:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 09:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:59:59' ;
11 121 1331
1.81980504467e-05 0.0 0.4 0.9
data at : 40 >>> 2007-01-15 10:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 09:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:14:59' ;
11 121 1331
0.00188992702176 1.0 0.9 0.0
data at : 41 >>> 2007-01-15 10:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 10:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:29:59' ;
11 121 1331
7.1599801145e-05 0.1 0.0 0.9
data at : 42 >>> 2007-01-15 10:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 10:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:44:59' ;
11 121 1331
1.4182711815e-05 0.5 0.3 0.1
data at : 43 >>> 2007-01-15 10:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 10:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:59:59' ;
11 121 1331
1.5141728925e-06 0.4 0.3 0.1
data at : 44 >>> 2007-01-15 11:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 10:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:14:59' ;
11 121 1331
1.26217744835e-29 1.0 1.0 0.0
data at : 45 >>> 2007-01-15 11:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 11:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:29:59' ;
11 121 1331
0.0 1.0 1.0 0.0
data at : 46 >>> 2007-01-15 11:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 11:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:44:59' ;
11 121 1331
0.00545753580417 0.3 0.5 0.8
data at : 47 >>> 2007-01-15 11:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 11:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:59:59' ;
11 121 1331
0.000281456374802 0.2 0.2 0.5
data at : 48 >>> 2007-01-15 12:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 11:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:14:59' ;
11 121 1331
4.01749757015e-05 0.1 0.3 0.5
data at : 49 >>> 2007-01-15 12:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 12:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:29:59' ;
11 121 1331
8.88003156769e-05 0.3 0.7 0.8
data at : 50 >>> 2007-01-15 12:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 12:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:44:59' ;
11 121 1331
0.00665694589647 0.2 0.2 1.0
data at : 51 >>> 2007-01-15 12:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 12:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:59:59' ;
11 121 1331
7.55871117889e-05 0.4 0.5 0.3
data at : 52 >>> 2007-01-15 13:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 12:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:14:59' ;
11 121 1331
0.00010667626587 0.4 0.4 0.9
data at : 53 >>> 2007-01-15 13:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 13:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:29:59' ;
11 121 1331
9.47441727843e-06 1.0 0.0 0.0
data at : 54 >>> 2007-01-15 13:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 13:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:44:59' ;
11 121 1331
0.0 1.0 1.0 0.0
data at : 55 >>> 2007-01-15 13:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 13:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:59:59' ;
11 121 1331
0.184059691883 0.1 0.9 0.5
data at : 56 >>> 2007-01-15 14:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 13:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:14:59' ;
11 121 1331
0.000152912489081 0.1 0.1 0.2
data at : 57 >>> 2007-01-15 14:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 14:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:29:59' ;
11 121 1331
0.0529095798595 1.0 0.7 0.7
data at : 58 >>> 2007-01-15 14:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 14:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:44:59' ;
11 121 1331
0.00043922272148 0.3 0.6 0.8
data at : 59 >>> 2007-01-15 14:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 14:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:59:59' ;
11 121 1331
0.000186092494505 0.5 0.3 1.0
data at : 60 >>> 2007-01-15 15:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 14:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:14:59' ;
11 121 1331
1.26217744835e-29 1.0 1.0 0.0
data at : 61 >>> 2007-01-15 15:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 15:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:29:59' ;
11 121 1331
0.000263679854374 0.2 0.4 0.8
data at : 62 >>> 2007-01-15 15:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 15:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:44:59' ;
11 121 1331
0.0125181423375 0.9 0.9 1.0
data at : 63 >>> 2007-01-15 15:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-15 15:44:59';