## PREDICTION MOVING METER2

In [1]:
#http://stackoverflow.com/questions/11845055/predicting-from-previous-datevalue-data
import matplotlib.pyplot as plt
import pandas as pd # v. 1.7
import MySQLdb
import numpy as np
import time
import sys
import datetime 
from datetime import datetime
from sympy import *
from sympy.solvers import solve
from sympy.parsing.sympy_parser import parse_expr
from sklearn.metrics import mean_absolute_error,mean_squared_error
import statistics 
%matplotlib inline

import MySQLdb
def initial_trend(series, slen):
    sum = 0.0
    for i in range(slen):
        sum += float(series[i+slen] - series[i]) / slen
    return sum / slen

# >>> initial_trend(series, 12)
# -0.7847222222222222

def triple_exponential_smoothing(series, slen, alpha, beta, gamma, n_preds):
    result = []
    seasonals = initial_seasonal_components(series, slen)
    for i in range(len(series)+n_preds):
        if i == 0: # initial values
            smooth = series[0]
            trend = initial_trend(series, slen)
            result.append(series[0])
            continue
        if i >= len(series): # we are forecasting
            m = i - len(series) + 1
            result.append((smooth + m*trend) + seasonals[i%slen])
        else:
            val = series[i]
            last_smooth, smooth = smooth, alpha*(val-seasonals[i%slen]) + (1-alpha)*(smooth+trend)
            trend = beta * (smooth-last_smooth) + (1-beta)*trend
            seasonals[i%slen] = gamma*(val-smooth) + (1-gamma)*seasonals[i%slen]
            result.append(smooth+trend+seasonals[i%slen])
    return result

# # forecast 24 points (i.e. two seasons)
# >>> triple_exponential_smoothing(series, 12, 0.716, 0.029, 0.993, 24)
# [30, 20.34449316666667, 28.410051892109554, 30.438122252647577, 39.466817731253066, ...


def initial_seasonal_components(series, slen):
    seasonals = {}
    season_averages = []
    n_seasons = int(len(series)/slen)
    # compute season averages
    for j in range(n_seasons):
        season_averages.append(sum(series[slen*j:slen*j+slen])/float(slen))
    # compute initial values
    for i in range(slen):
        sum_of_vals_over_avg = 0.0
        for j in range(n_seasons):
            sum_of_vals_over_avg += series[slen*j+i]-season_averages[j]
        seasonals[i] = sum_of_vals_over_avg/n_seasons
    return seasonals
##-----------------------------------------------------------------------------------
from sklearn.metrics import mean_squared_error
def fittingparameter(data_y,j):
    count_alpha = 0
    count_beta = 0
    count_gamma = 0
    alpha = float(0)
    beta = float(0)
    gamma = float(0)
    index_alpha =[]
    index_beta =[]
    index_gamma = []
    act = j
    data = data_y
    pred_no = 1
    ramda = 0.1
    MSE_holtload = []
#     query1 = "SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '%s' AND TimeStamp <= '%s';"% (time_b[act+1],time_b[act+96])
    query1 = "SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '%s' ;"% (time_b[act+1])
    print query1
    df1 = pd.read_sql(query1, conn)
#     print len(df)
    while (alpha <= float(1)):
        count_alpha += 1
        beta = float(0)
        while (beta <=float(1)):
            count_beta += 1 
            gamma = float(0)
            while (gamma <= float(1)):
                count_gamma += 1
                pred_h = triple_exponential_smoothing(data, 96*7,alpha,beta ,gamma, pred_no)
                pred_data = pred_h[len(pred_h)-(pred_no):]                                               
                MSE = mean_squared_error (df1.Sub_metering_2, pred_data)   
#                 print MSE              
                MSE_holtload.append(MSE)
                index_alpha.append(alpha)
                index_beta.append(beta)
                index_gamma.append(gamma)     
#                 print index_alpha,index_beta,index_gamma
                gamma += ramda
            beta += ramda
        alpha += ramda  
#     print  count_gamma,count_beta,count_alpha    
    index_MSE = MSE_holtload.index(min(MSE_holtload))
#     print min(MSE_holtload)
#     print index_MSE
    MSE_min = MSE_holtload[index_MSE]
    alpha = index_alpha[index_MSE]
    beta = index_beta[index_MSE]
    gamma= index_gamma[index_MSE]
    print count_alpha,count_beta,count_gamma
    print MSE_min,alpha,beta,gamma
    return (alpha,beta,gamma)

In [3]:
conn = MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()
query = "SELECT Timestamp,active_power FROM prediction.data15min_4y WHERE Timestamp >= '%s'   AND TimeStamp <= '%s';"% ("2007-01-01 00:14:59","2007-03-31 23:59:59")
df = pd.read_sql(query, conn , index_col=['Timestamp'])

pred_no = 1 # power 1 Data/15min in 1Hr --> 60/15 = 4 and 1day = 4*24 = 96
j = 0
i = 0
d = len(df)/96 
day = 0

conn = MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()

time_a = pd.date_range('2007-01-01 00:14:59', periods=d*96, freq='15T')
time_b = pd.date_range('2007-01-14 23:59:59', periods=(d*96)+1, freq='15T')

# set databases to empty 
query_empty = """truncate table prediction.pred_moving_mt2""" 
c.execute(query_empty)

while (j < 96*d ) :    
    if (j%96 == 0):    
        day += 1
        print "______________DAY:" , day

    print "\ndata at :" , j,">>>", time_b[j+1]
    query = "SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '%s'   AND TimeStamp <= '%s';"% (time_a[j],time_b[j])
    print query
    df = pd.read_sql(query, conn)
    conn.commit()
    data_y = df['Sub_metering_2'].values.tolist()  
    ans_fiting = fittingparameter(data_y,j)
    pred_h = triple_exponential_smoothing(data_y, 96*7, ans_fiting[0], ans_fiting[1], ans_fiting[2],1)
    pred_data = pred_h[len(pred_h)-(pred_no):]
    c.execute("INSERT INTO prediction.pred_moving_mt2 (Timestamp, watt_sub2) VALUES ( %s, %s)",(time_b[j+1],abs(pred_data[0])))
    conn.commit()
    j += 1
print "DONE!!"

______________DAY: 1

data at : 0 >>> 2007-01-15 00:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:14:59'   AND TimeStamp <= '2007-01-14 23:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:14:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 1 >>> 2007-01-15 00:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:29:59'   AND TimeStamp <= '2007-01-15 00:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:29:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 2 >>> 2007-01-15 00:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:44:59'   AND TimeStamp <= '2007-01-15 00:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:44:59' ;
11 121 1331
0.00671071596263 0.4 0.5 0.1

data at : 3 >>> 2007-01-15 00:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 00:59:59'   AND TimeStamp <= '2007-01-15 00:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 00:59:59' ;
11 121 1331
0.00136386273349 0.3 0.0 0.6

data at : 4 >>> 2007-01-15 01:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 01:14:59'   AND TimeStamp <= '2007-01-15 00:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:14:59' ;
11 121 1331
8.10836554183e-05 0.2 0.1 0.1

data at : 5 >>> 2007-01-15 01:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 01:29:59'   AND TimeStamp <= '2007-01-15 01:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:29:59' ;
11 121 1331
0.0236108321667 0.4 0.8 0.7

data at : 6 >>> 2007-01-15 01:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 01:44:59'   AND TimeStamp <= '2007-01-15 01:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:44:59' ;
11 121 1331
0.000514291980524 0.3 0.0 0.0

data at : 7 >>> 2007-01-15 01:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 01:59:59'   AND TimeStamp <= '2007-01-15 01:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 01:59:59' ;
11 121 1331
0.000256420119507 0.8 1.0 0.3

data at : 8 >>> 2007-01-15 02:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 02:14:59'   AND TimeStamp <= '2007-01-15 01:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:14:59' ;
11 121 1331
3.35803168969e-06 0.2 0.3 0.9

data at : 9 >>> 2007-01-15 02:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 02:29:59'   AND TimeStamp <= '2007-01-15 02:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:29:59' ;
11 121 1331
0.000137164007011 0.3 0.4 0.2

data at : 10 >>> 2007-01-15 02:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 02:44:59'   AND TimeStamp <= '2007-01-15 02:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:44:59' ;
11 121 1331
0.113884611389 0.1 0.1 0.1

data at : 11 >>> 2007-01-15 02:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 02:59:59'   AND TimeStamp <= '2007-01-15 02:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 02:59:59' ;
11 121 1331
1.08803993954e-06 0.8 0.6 0.6

data at : 12 >>> 2007-01-15 03:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 03:14:59'   AND TimeStamp <= '2007-01-15 02:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:14:59' ;
11 121 1331
0.000111769245142 0.6 0.1 0.4

data at : 13 >>> 2007-01-15 03:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 03:29:59'   AND TimeStamp <= '2007-01-15 03:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:29:59' ;
11 121 1331
0.000353524045701 0.3 0.8 0.1

data at : 14 >>> 2007-01-15 03:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 03:44:59'   AND TimeStamp <= '2007-01-15 03:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:44:59' ;
11 121 1331
0.000191821577502 0.9 0.5 0.1

data at : 15 >>> 2007-01-15 03:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 03:59:59'   AND TimeStamp <= '2007-01-15 03:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 03:59:59' ;
11 121 1331
1.78111903317e-08 0.6 0.5 0.3

data at : 16 >>> 2007-01-15 04:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 04:14:59'   AND TimeStamp <= '2007-01-15 03:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:14:59' ;
11 121 1331
8.61542480362e-07 0.9 0.4 0.2

data at : 17 >>> 2007-01-15 04:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 04:29:59'   AND TimeStamp <= '2007-01-15 04:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:29:59' ;
11 121 1331
0.00187685810376 0.3 0.6 0.6

data at : 18 >>> 2007-01-15 04:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 04:44:59'   AND TimeStamp <= '2007-01-15 04:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:44:59' ;
11 121 1331
0.00651374011566 0.2 0.0 0.8

data at : 19 >>> 2007-01-15 04:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 04:59:59'   AND TimeStamp <= '2007-01-15 04:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 04:59:59' ;
11 121 1331
0.00517268944753 0.2 0.5 0.1

data at : 20 >>> 2007-01-15 05:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 05:14:59'   AND TimeStamp <= '2007-01-15 04:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:14:59' ;
11 121 1331
1.73871657663e-07 0.6 0.1 0.2

data at : 21 >>> 2007-01-15 05:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 05:29:59'   AND TimeStamp <= '2007-01-15 05:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:29:59' ;
11 121 1331
1.48872089914e-05 0.3 0.3 1.0

data at : 22 >>> 2007-01-15 05:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 05:44:59'   AND TimeStamp <= '2007-01-15 05:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:44:59' ;
11 121 1331
4.48331161842e-06 0.3 0.5 0.3

data at : 23 >>> 2007-01-15 05:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 05:59:59'   AND TimeStamp <= '2007-01-15 05:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 05:59:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 24 >>> 2007-01-15 06:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 06:14:59'   AND TimeStamp <= '2007-01-15 05:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:14:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 25 >>> 2007-01-15 06:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 06:29:59'   AND TimeStamp <= '2007-01-15 06:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:29:59' ;
11 121 1331
0.0514518621321 0.2 0.8 0.6

data at : 26 >>> 2007-01-15 06:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 06:44:59'   AND TimeStamp <= '2007-01-15 06:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:44:59' ;
11 121 1331
2.85683731931e-05 0.3 1.0 0.4

data at : 27 >>> 2007-01-15 06:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 06:59:59'   AND TimeStamp <= '2007-01-15 06:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 06:59:59' ;
11 121 1331
0.0125556471971 0.1 0.2 0.8

data at : 28 >>> 2007-01-15 07:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 07:14:59'   AND TimeStamp <= '2007-01-15 06:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:14:59' ;
11 121 1331
0.00093971442743 0.0 0.0 0.4

data at : 29 >>> 2007-01-15 07:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 07:29:59'   AND TimeStamp <= '2007-01-15 07:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:29:59' ;
11 121 1331
3.39199732273e-05 0.1 0.2 0.2

data at : 30 >>> 2007-01-15 07:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 07:44:59'   AND TimeStamp <= '2007-01-15 07:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:44:59' ;
11 121 1331
0.00013513855166 0.7 0.7 0.3

data at : 31 >>> 2007-01-15 07:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 07:59:59'   AND TimeStamp <= '2007-01-15 07:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 07:59:59' ;
11 121 1331
8.47234930704e-06 0.4 0.7 0.7

data at : 32 >>> 2007-01-15 08:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 08:14:59'   AND TimeStamp <= '2007-01-15 07:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:14:59' ;
11 121 1331
2.70688652719e-05 0.4 1.0 0.8

data at : 33 >>> 2007-01-15 08:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 08:29:59'   AND TimeStamp <= '2007-01-15 08:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:29:59' ;
11 121 1331
0.00152930017492 0.3 1.0 0.8

data at : 34 >>> 2007-01-15 08:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 08:44:59'   AND TimeStamp <= '2007-01-15 08:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:44:59' ;
11 121 1331
0.00136847244194 0.1 0.0 0.2

data at : 35 >>> 2007-01-15 08:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 08:59:59'   AND TimeStamp <= '2007-01-15 08:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 08:59:59' ;
11 121 1331
8.23631429612e-06 1.0 0.0 0.0

data at : 36 >>> 2007-01-15 09:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 09:14:59'   AND TimeStamp <= '2007-01-15 08:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:14:59' ;
11 121 1331
4.61165057557e-06 0.9 0.4 0.3

data at : 37 >>> 2007-01-15 09:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 09:29:59'   AND TimeStamp <= '2007-01-15 09:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:29:59' ;
11 121 1331
3.08906715148e-06 0.1 0.2 0.7

data at : 38 >>> 2007-01-15 09:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 09:44:59'   AND TimeStamp <= '2007-01-15 09:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:44:59' ;
11 121 1331
7.0942745089e-05 0.6 0.2 0.2

data at : 39 >>> 2007-01-15 09:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 09:59:59'   AND TimeStamp <= '2007-01-15 09:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 09:59:59' ;
11 121 1331
0.0362811791383 0.0 0.8 1.0

data at : 40 >>> 2007-01-15 10:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 10:14:59'   AND TimeStamp <= '2007-01-15 09:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:14:59' ;
11 121 1331
0.00138395702366 0.1 0.7 0.3

data at : 41 >>> 2007-01-15 10:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 10:29:59'   AND TimeStamp <= '2007-01-15 10:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:29:59' ;
11 121 1331
0.0163779053285 0.0 0.0 1.0

data at : 42 >>> 2007-01-15 10:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 10:44:59'   AND TimeStamp <= '2007-01-15 10:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:44:59' ;
11 121 1331
1.72619223769e-05 0.1 0.0 0.3

data at : 43 >>> 2007-01-15 10:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 10:59:59'   AND TimeStamp <= '2007-01-15 10:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 10:59:59' ;
11 121 1331
4.78260571319e-06 0.8 0.3 0.6

data at : 44 >>> 2007-01-15 11:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 11:14:59'   AND TimeStamp <= '2007-01-15 10:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:14:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 45 >>> 2007-01-15 11:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 11:29:59'   AND TimeStamp <= '2007-01-15 11:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:29:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 46 >>> 2007-01-15 11:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 11:44:59'   AND TimeStamp <= '2007-01-15 11:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:44:59' ;
11 121 1331
0.000424090583518 0.5 0.7 0.2

data at : 47 >>> 2007-01-15 11:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 11:59:59'   AND TimeStamp <= '2007-01-15 11:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 11:59:59' ;
11 121 1331
4.15840196128e-05 0.4 0.1 0.2

data at : 48 >>> 2007-01-15 12:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 12:14:59'   AND TimeStamp <= '2007-01-15 11:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:14:59' ;
11 121 1331
0.0010240187075 0.1 0.3 0.0

data at : 49 >>> 2007-01-15 12:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 12:29:59'   AND TimeStamp <= '2007-01-15 12:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:29:59' ;
11 121 1331
2.54064336543e-06 0.6 0.6 0.9

data at : 50 >>> 2007-01-15 12:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 12:44:59'   AND TimeStamp <= '2007-01-15 12:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:44:59' ;
11 121 1331
4.30277876491e-05 0.1 0.5 0.0

data at : 51 >>> 2007-01-15 12:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 12:59:59'   AND TimeStamp <= '2007-01-15 12:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 12:59:59' ;
11 121 1331
2.12010631973e-05 0.3 0.5 0.7

data at : 52 >>> 2007-01-15 13:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 13:14:59'   AND TimeStamp <= '2007-01-15 12:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:14:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 53 >>> 2007-01-15 13:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 13:29:59'   AND TimeStamp <= '2007-01-15 13:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:29:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 54 >>> 2007-01-15 13:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 13:44:59'   AND TimeStamp <= '2007-01-15 13:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:44:59' ;
11 121 1331
0.0 1.0 1.0 0.0

data at : 55 >>> 2007-01-15 13:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 13:59:59'   AND TimeStamp <= '2007-01-15 13:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 13:59:59' ;
11 121 1331
1.37916127367 0.1 0.9 0.7

data at : 56 >>> 2007-01-15 14:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 14:14:59'   AND TimeStamp <= '2007-01-15 13:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:14:59' ;
11 121 1331
2.06778232289e-05 0.1 0.7 0.0

data at : 57 >>> 2007-01-15 14:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 14:29:59'   AND TimeStamp <= '2007-01-15 14:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:29:59' ;
11 121 1331
0.00891981087381 0.8 1.0 0.8

data at : 58 >>> 2007-01-15 14:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 14:44:59'   AND TimeStamp <= '2007-01-15 14:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:44:59' ;
11 121 1331
1.44488647236e-05 0.4 0.2 0.4

data at : 59 >>> 2007-01-15 14:59:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 14:59:59'   AND TimeStamp <= '2007-01-15 14:44:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 14:59:59' ;
11 121 1331
2.99519638401e-06 0.8 0.0 0.8

data at : 60 >>> 2007-01-15 15:14:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 15:14:59'   AND TimeStamp <= '2007-01-15 14:59:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:14:59' ;
11 121 1331
3.13151190637e-08 0.3 0.8 0.2

data at : 61 >>> 2007-01-15 15:29:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 15:29:59'   AND TimeStamp <= '2007-01-15 15:14:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:29:59' ;
11 121 1331
0.000566745317764 0.6 0.2 0.1

data at : 62 >>> 2007-01-15 15:44:59
SELECT Timestamp,Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp >= '2007-01-01 15:44:59'   AND TimeStamp <= '2007-01-15 15:29:59';
SELECT Sub_metering_2 FROM prediction.data15min_4y WHERE Timestamp = '2007-01-15 15:44:59' ;
11 121 1331
0.000154661881419 0.5 0.6 0.8

data at : 63 >>> 2007-01-15 15:59:59