In [12]:
"""
ค่าไฟฟ้ารายเดือน 
"""

import pandas as pd
import matplotlib.pyplot as plt
import MySQLdb
import time

from sympy import *
from sympy.solvers import solve
from sympy.parsing.sympy_parser import parse_expr

time_a = pd.date_range("00:00:00", "23:45:00", freq="15min")
time_b = pd.date_range("00:14:59", "23:59:59", freq="15min")

 # GET DATA 
conn= MySQLdb.connect("localhost","conn","hems","power")
c = conn.cursor()

####### set databases_monthly_fee to empty #########
query_empty = """truncate table watt.electricity_bill""" 
c.execute(query_empty)
print "watt.electricity_bill are Empty!!! \n"


dict = {'January': 31, 'February': 28, 'March': 31 ,
        'April': 30 ,'May': 31 ,'June': 30,
        'July': 31,'August': 31 ,'September': 30 ,
        'October': 31 ,'November': 30 , 'December': 31}   
turn = dict[time.strftime('%B')]
# print turn

    
x = raw_input('What about Ft?')
Ft = float(x)
t1 = 3.2484
t2 = 4.2218
t3 = 4.4217
ser = 38.22
u = symbols('u')


def bill(allpow):    
    ## Fundamental parameter
    if 1 <= allpow <= 150:
        bath = allpow*t1
    elif  151 <= allpow <= 400:
        power = allpow-150
        bath_1 = 150*t1
        bath_2 = power*t2
        bath = bath_1+bath_2
    else:
        power = allpow-150
        bath_1 = 150*t1
        power = power-250
        bath_2 = 250*t2
        bath_3 = power*t3
        bath = bath_1+bath_2+bath_3   
    service_price = 38.22  #permonth (fixed)
   
    ## FT -33.2 satang/unit
    FT_price = allpow*Ft

    ## VAT 7%
    VAT_price = ((service_price+bath)+FT_price)*0.07

    bill = bath+service_price+FT_price+VAT_price

    print "bill of this month equal to",round(bill,2)," bath"
    return
       

def inbill(bath):
    test_1 = solve(Eq((u*t1)+ser+(u*Ft)+(0.07*((u*t1)+ser))+(0.07*(u*Ft)),bath))
#     print test_1
    test_2 = solve(Eq((150*t1)+((u-150)*t2)+ser+(u*Ft)+(0.07*((150*t1)+((u-150)*t2)+ser))+(0.07*(u*Ft)),bath))
#     print test_2
    test_3 = solve(Eq((150*t1)+(250*t2)+((u-400)*t3)+ser+(u*Ft)+(0.07*((150*t1)+(250*t2)+((u-400)*t3)+ser))+(0.07*(u*Ft)),bath))
#     print test_3

    if 1 <=  test_1[0] <= 150:
        unit = test_1[0]
    elif 151 <=  test_2[0] <=  400:
        unit = test_2[0]
    else:
        unit = test_3[0]
    print "all unit of this month equal to",round(unit),"KW/Hr"
    return
    
  
inbill(1797.41)
bill(427)

watt.electricity_bill are Empty!!!

all unit of this month equal to 427.0 KW/Hr
bill of this month equal to 1797.41  bath

In [ ]:
###### TEST #################
...

...

FT = -0.0480 
allpow = 150
## primary 
if 1 <= allpow <= 150:
    bath = allpow*3.2484
elif  151 <= allpow <= 400:
    power = allpow-150
    bath_1 = 150*3.2484
    bath_2 = power*4.2218
    bath = bath_1+bath_2
else:
    power = allpow-150
    bath_1 = 150*3.2484
    power = power-250
    bath_2 = 250*4.2218
    bath_3 = power*4.4217
    bath = bath_1+bath_2+bath_3   
service_price = 38.22  #permonth (fixed)

## FT -33.2 satang/unit
FT_price = allpow*FT

## VAT 7%
VAT_price = ((service_price+bath)+FT_price)*0.07

bill = bath+service_price+FT_price+VAT_price

print "bill of this month equal to",bill," bath"

In [ ]:
###### TEST #################
...

...

Ft = -0.3329
t1 = 3.2484
t2 = 4.2218
t3 = 4.4217
ser = 38.22
u = symbols('u')
bath = 1507.50

test_1 = solve(Eq((u*t1)+ser+(u*Ft)+(0.07*((u*t1)+ser))+(0.07*(u*Ft)),bath))
print test_1
test_2 = solve(Eq((150*t1)+((u-150)*t2)+ser+(u*Ft)+(0.07*((150*t1)+((u-150)*t2)+ser))+(0.07*(u*Ft)),bath))
print test_2
test_3 = solve(Eq((150*t1)+(250*t2)+((u-400)*t3)+ser+(u*Ft)+(0.07*((150*t1)+(250*t2)+((u-400)*t3)+ser))+(0.07*(u*Ft)),bath))
print test_3

if 1 <=  test_1[0] <= 150:
    unit = test_1[0]
elif (151 <=  test_2[0] <=  400):
    unit = test_2[0]
else:
    unit = test_3[0]
print "all unit of this month equal to",round(unit),"KW/Hr"

In [ ]:
invbill(390)
def invbill(bath):
    test_1 = solve(Eq((u*t1)+ser+(u*Ft)+(0.07*((u*t1)+ser))+(0.07*(u*Ft)),bath))
    print test_1
    test_2 = solve(Eq((150*t1)+((u-150)*t2)+ser+(u*Ft)+(0.07*((150*t1)+((u-150)*t2)+ser))+(0.07*(u*Ft)),bath))
    print test_2
    test_3 = solve(Eq((150*t1)+(250*t2)+((u-400)*t3)+ser+(u*Ft)+(0.07*((150*t1)+(250*t2)+((u-400)*t3)+ser))+(0.07*(u*Ft)),bath))
    print test_3

    if 1 <=  test_1[0] <= 150:
        unit = test_1[0]
    elif (151 <=  test_2[0] <=  400):
        unit = test_2[0]
    else:
        unit = test_3[0]
    print "all unit of this month equal to",round(unit),"KW/Hr"
    return