
# data_TIMELInE
### Microwave | ขนาด 400W |

In [1]:
import pandas as pd
import MySQLdb
import numpy as np
import time
import datetime 
import random


d = 31
time_a = pd.date_range('2016-10-01 00:00:00', periods=5760*d, freq='15S')
# print time_a
time_b = pd.date_range('2016-10-01 00:00:14', periods=5760*d, freq='15S')
# print time_b

conn= MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()

####### set databases to empty #########
query_empty = """truncate table data_timeline.Microwave""" 
c.execute(query_empty)
print "data_timeline.Microwave are Empty!!! \n"

query = "SELECT watt FROM collected_info.12_Microwave WHERE no >= '%s'   AND no <= '%s'; "% (0,1300)
df = pd.read_sql(query, conn)
# print df.watt[5]

#### Random the turning-on time appliances
def rand_turnon():
    duration_sec =  random.randint(0, 59)
    duration_min =  random.randint(0, 59)
    duration_hour1 = ['18'] * 40 + ['19'] * 45 + ['20'] * 12 + ['21'] * 3
    duration_hour = random.choice(duration_hour1)     
    if 0 < duration_sec <= 15:
        k = 0
    elif 15 < duration_sec <= 30:
        k = 1
    elif 30 < duration_sec <= 45:
        k = 2
    else:
        k = 3
    off_item = (int(duration_hour)*240) + (int(duration_min)*4)+ k 
    print "time to turn-on appliacne on",duration_hour,":",duration_min,":",duration_sec,"equal to",off_item,"items"
    return off_item

 
#### Random the off-duration appliances 
def rand_duration():
    duration_sec =  random.randint(0, 59)
    duration_min =  random.randint(10, 40)
    duration_hour1 = ['0'] * 50 + ['0'] * 1+ ['0'] * 49
    duration_hour = random.choice(duration_hour1)   
    seconds = (int(duration_hour)*3600)+(duration_min*60)+duration_sec
    no_item = seconds/15
    print "consuming the appliance", duration_hour,"hours",duration_min,"minutes",duration_sec,"seconds that equal to",seconds,"seconds or",no_item,"items"
    return no_item

days = 0
j = 0
i = 0
print "\nDays :",days ,":",time_b[j].strftime('%a')
off_item = rand_turnon()  
no_item = rand_duration()  

while (j <= (5760*d)-1):  
    c.execute("INSERT INTO data_timeline.Microwave (Timestamp, watt) VALUES (%s, %s)",(time_b[j],0))
    conn.commit()
    j += 1 
    
    while (off_item+(5760*(days)) <= j <= (no_item+off_item)+(5760*(days))):                   
        c.execute("INSERT INTO data_timeline.Microwave (Timestamp, watt) VALUES (%s, %s)",(time_b[j],df.watt[i]))
        conn.commit()
        i += 1 
        j += 1
        if (j == (no_item+off_item)+(5760*(days))):
            days +=1
            print "\nDays :",days ,":",time_b[j].strftime('%a')
            off_item = rand_turnon()  
            no_item = rand_duration() 
            i= 0   

                    
print "DONE!"

data_timeline.Microwave are Empty!!!


Days : 0 : Sat
time to turn-on appliacne on 18 : 12 : 22 equal to 4369 items
consuming the appliance 0 hours 37 minutes 29 seconds that equal to 2249 seconds or 149 items

Days : 1 : Sat
time to turn-on appliacne on 19 : 27 : 14 equal to 4668 items
consuming the appliance 0 hours 23 minutes 42 seconds that equal to 1422 seconds or 94 items

Days : 2 : Sun
time to turn-on appliacne on 19 : 31 : 27 equal to 4685 items
consuming the appliance 0 hours 11 minutes 1 seconds that equal to 661 seconds or 44 items

Days : 3 : Mon
time to turn-on appliacne on 18 : 1 : 43 equal to 4326 items
consuming the appliance 0 hours 28 minutes 33 seconds that equal to 1713 seconds or 114 items

Days : 4 : Tue
time to turn-on appliacne on 19 : 34 : 32 equal to 4698 items
consuming the appliance 0 hours 38 minutes 37 seconds that equal to 2317 seconds or 154 items

Days : 5 : Wed
time to turn-on appliacne on 19 : 23 : 53 equal to 4655 items
consuming the appliance 0 hours 14 minutes 17 seconds that equal to 857 seconds or 57 items

Days : 6 : Thu
time to turn-on appliacne on 19 : 20 : 52 equal to 4643 items
consuming the appliance 0 hours 18 minutes 15 seconds that equal to 1095 seconds or 73 items

Days : 7 : Fri
time to turn-on appliacne on 19 : 36 : 25 equal to 4705 items
consuming the appliance 0 hours 40 minutes 29 seconds that equal to 2429 seconds or 161 items

Days : 8 : Sat
time to turn-on appliacne on 19 : 1 : 53 equal to 4567 items
consuming the appliance 0 hours 27 minutes 4 seconds that equal to 1624 seconds or 108 items

Days : 9 : Sun
time to turn-on appliacne on 18 : 54 : 4 equal to 4536 items
consuming the appliance 0 hours 25 minutes 2 seconds that equal to 1502 seconds or 100 items

Days : 10 : Mon
time to turn-on appliacne on 18 : 28 : 39 equal to 4434 items
consuming the appliance 0 hours 29 minutes 29 seconds that equal to 1769 seconds or 117 items

Days : 11 : Tue
time to turn-on appliacne on 18 : 12 : 11 equal to 4368 items
consuming the appliance 0 hours 14 minutes 59 seconds that equal to 899 seconds or 59 items

Days : 12 : Wed
time to turn-on appliacne on 18 : 15 : 33 equal to 4382 items
consuming the appliance 0 hours 35 minutes 55 seconds that equal to 2155 seconds or 143 items

Days : 13 : Thu
time to turn-on appliacne on 21 : 39 : 46 equal to 5199 items
consuming the appliance 0 hours 23 minutes 46 seconds that equal to 1426 seconds or 95 items

Days : 14 : Fri
time to turn-on appliacne on 19 : 36 : 49 equal to 4707 items
consuming the appliance 0 hours 24 minutes 3 seconds that equal to 1443 seconds or 96 items

Days : 15 : Sat
time to turn-on appliacne on 19 : 32 : 45 equal to 4690 items
consuming the appliance 0 hours 38 minutes 39 seconds that equal to 2319 seconds or 154 items

Days : 16 : Sun
time to turn-on appliacne on 19 : 51 : 36 equal to 4766 items
consuming the appliance 0 hours 21 minutes 1 seconds that equal to 1261 seconds or 84 items

Days : 17 : Mon
time to turn-on appliacne on 19 : 51 : 5 equal to 4764 items
consuming the appliance 0 hours 15 minutes 5 seconds that equal to 905 seconds or 60 items

Days : 18 : Tue
time to turn-on appliacne on 18 : 26 : 7 equal to 4424 items
consuming the appliance 0 hours 22 minutes 49 seconds that equal to 1369 seconds or 91 items

Days : 19 : Wed
time to turn-on appliacne on 20 : 41 : 37 equal to 4966 items
consuming the appliance 0 hours 24 minutes 3 seconds that equal to 1443 seconds or 96 items

Days : 20 : Thu
time to turn-on appliacne on 18 : 58 : 46 equal to 4555 items
consuming the appliance 0 hours 26 minutes 50 seconds that equal to 1610 seconds or 107 items

Days : 21 : Fri
time to turn-on appliacne on 18 : 39 : 52 equal to 4479 items
consuming the appliance 0 hours 14 minutes 48 seconds that equal to 888 seconds or 59 items

Days : 22 : Sat
time to turn-on appliacne on 20 : 53 : 41 equal to 5014 items
consuming the appliance 0 hours 34 minutes 11 seconds that equal to 2051 seconds or 136 items

Days : 23 : Sun
time to turn-on appliacne on 18 : 44 : 7 equal to 4496 items
consuming the appliance 0 hours 31 minutes 57 seconds that equal to 1917 seconds or 127 items

Days : 24 : Mon
time to turn-on appliacne on 21 : 54 : 31 equal to 5258 items
consuming the appliance 0 hours 32 minutes 52 seconds that equal to 1972 seconds or 131 items

Days : 25 : Tue
time to turn-on appliacne on 19 : 23 : 19 equal to 4653 items
consuming the appliance 0 hours 12 minutes 3 seconds that equal to 723 seconds or 48 items

Days : 26 : Wed
time to turn-on appliacne on 18 : 6 : 42 equal to 4346 items
consuming the appliance 0 hours 38 minutes 58 seconds that equal to 2338 seconds or 155 items

Days : 27 : Thu
time to turn-on appliacne on 19 : 4 : 31 equal to 4578 items
consuming the appliance 0 hours 17 minutes 54 seconds that equal to 1074 seconds or 71 items

Days : 28 : Fri
time to turn-on appliacne on 18 : 20 : 36 equal to 4402 items
consuming the appliance 0 hours 31 minutes 13 seconds that equal to 1873 seconds or 124 items

Days : 29 : Sat
time to turn-on appliacne on 18 : 16 : 26 equal to 4385 items
consuming the appliance 0 hours 40 minutes 21 seconds that equal to 2421 seconds or 161 items

Days : 30 : Sun
time to turn-on appliacne on 18 : 43 : 8 equal to 4492 items
consuming the appliance 0 hours 21 minutes 32 seconds that equal to 1292 seconds or 86 items

Days : 31 : Mon
time to turn-on appliacne on 18 : 59 : 15 equal to 4556 items
consuming the appliance 0 hours 25 minutes 41 seconds that equal to 1541 seconds or 102 items
DONE!

In [1]:
import pandas as pd
import MySQLdb
import numpy as np
import time
import datetime 
import random
import matplotlib.pyplot as plt
%matplotlib inline  


# query = "SELECT watt FROM device.aircont WHERE Timestamp >= '%s'   AND Timestamp <= '%s'; "% (time_a[0],time_b[j-1])
query = "SELECT Timestamp,watt FROM data_timeline.Microwave WHERE Timestamp >= '%s'   AND Timestamp <= '%s'; "% (time_a[0],time_b[j-1])
df = pd.read_sql(query, conn, index_col=['Timestamp'])
fig, ax = plt.subplots()
ax.set_title('data_timeline.Microwave')
df.plot(ax=ax )
plt.show()

NameError: name 'time_a' is not defined