In [2]:
import MySQLdb
import time
import datetime
import re
import urllib2
import socket
import matplotlib.pyplot as plt
from statistics import mean
import numpy as np

#---- For matplotlib plot in web -----
%matplotlib inline

In [7]:
conn= MySQLdb.connect("52.220.88.45","read","hems","power")
c = conn.cursor()

c.execute("SELECT s11  FROM power.enegate_bkk WHERE Timestamp >= '2016-08-12 00:00:00' AND Timestamp < '2016-08-12 01:00:00' ")
results = c.fetchall()

# power = []
# time = []
# i = 0
# for row in results:
#     if row[0] == "----":   # find data in dataframe /= 0< (data = "----")
# 	   print row[0]        #print it out
#     else :power.append(row[0])
# print len(power)

# for i in range(len(power)):
#     time.append(i+1)

# plt.scatter(time,power)
# plt.show()

conn.commit()
print results

(('1968',), ('1968',), ('1968',), ('1968',), ('1968',), ('1968',), ('1968',), ('1824',), ('1824',), ('1800',), ('1776',), ('1776',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1800',), ('1800',), ('1824',), ('1776',), ('1776',), ('1800',), ('1824',), ('1824',), ('1824',), ('1824',), ('1800',), ('1800',), ('1800',), ('1752',), ('1752',), ('1800',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1728',), ('1776',), ('1728',), ('1728',), ('1752',), ('1752',), ('1752',), ('1728',), ('1752',), ('1752',), ('1752',), ('1752',), ('1752',), ('1752',), ('1752',), ('1776',), ('1776',), ('1776',), ('1776',), ('1800',), ('1752',), ('1776',), ('1848',), ('1824',), ('1824',), ('1800',), ('1824',), ('1824',), ('1848',), ('1848',), ('1800',), ('1800',), ('1824',), ('1824',), ('1800',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1824',), ('1800',), ('1800',), ('1824',), ('1824',), ('1824',), ('1824',), ('1800',), ('1800',), ('1800',), ('1824',), ('1824',), ('1800',), ('1992',), ('2016',), ('1992',), ('1992',), ('1968',), ('1992',), ('1992',), ('1920',), ('1848',), ('1872',), ('1872',), ('1896',), ('1920',), ('1920',), ('1896',), ('1872',), ('1872',), ('1848',), ('1872',), ('1872',), ('1872',), ('1872',), ('1848',), ('1824',), ('1824',), ('1824',), ('1872',), ('1872',), ('1824',), ('1824',), ('1896',), ('1896',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1920',), ('1944',), ('1944',), ('1944',), ('1968',), ('1944',), ('1944',), ('1944',), ('1920',), ('1944',), ('1920',), ('1944',), ('1944',), ('1944',), ('1944',), ('1920',), ('1920',), ('1920',), ('1920',), ('1920',), ('1896',), ('1920',), ('1896',), ('1872',), ('1872',), ('1872',), ('1872',), ('1872',), ('1944',), ('1896',), ('1896',), ('1920',), ('1920',), ('1920',), ('1848',), ('1824',), ('1824',), ('1824',), ('1848',), ('1776',), ('1776',), ('1824',), ('1824',), ('1872',), ('1896',), ('1896',), ('1896',), ('1896',), ('1896',), ('1872',), ('1896',), ('1896',), ('1896',), ('1896',), ('1896',), ('1944',), ('1944',), ('1968',), ('1968',), ('1968',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1968',), ('1944',), ('1968',), ('1920',), ('1920',), ('1920',), ('1968',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1944',), ('1920',), ('1944',), ('1920',), ('1920',), ('1920',), ('1920',), ('1896',), ('1920',), ('1920',), ('1920',), ('1944',), ('1944',), ('1944',), ('1944',), ('1896',), ('1872',), ('1872',), ('1824',), ('1872',), ('1896',))